name: Linux Build
on: push
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: f7bb59d9f51cc10b25ff86d34a3eff744e60c46e
    - name: Install dependencies
      run: | 
        sudo apt install libx11-dev libxcb-composite0-dev libxcb-randr0-dev libxcb-xkb-dev libasound2-dev libqt5network5 libqt5svg5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtbase5-dev libqt5widgets5
        sudo apt install libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5 libqt5dbus5 qtbase5-dev qtbase5-dev-tools
        sudo apt-get install git g++ make libtool automake autopoint pkg-config flex bison lua5.2 gettext libmpeg2-4-dev liba52-0.7.4-dev
        sudo apt-get install subversion yasm cvs cmake ragel ninja-build meson liblua5.2-dev libavdevice-dev libdvbpsi-dev libdvdnav4
    - name: Run build
      run: |
        ./bootstrap
        ./configure
        make
